baseurl: /
languageCode: en-us
title: Ocean
theme: "hugo-theme-minos"
googleAnalytics: ''
disqusShortname: ''
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - \.knit\.md$
  - \.utf8\.md$
permalinks:
  post: /:year/:month/:day/:slug/
menu:
  main:
    - name: About
      url: /about/
    - name: Révolte indienne
      url: https://lareleveetlapeste.fr/apres-un-an-de-revolte-les-paysans-indiens-obtiennent-le-retrait-de-la-reforme-polemique/
    - name: Day to night photography
      url: https://waitbutwhy.com/2016/06/incredible-day-to-night-photography.html
params:
  MathJaxCDN: //cdnjs.cloudflare.com/ajax/libs
  MathJaxVersion: 2.7.5
  description: A website about something not defined yet.
  favicon: "logo.png"
  highlightjsCDN: //cdnjs.cloudflare.com/ajax/libs
  highlightjsLang:
    - r
    - yaml
  highlightjsTheme: github
  highlightjsVersion: 9.12.0
  logo:
    alt: Logo
    height: 50
    url: logo.png
    width: 50
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: yes
